version: '3.8'

services:
  ravenpoint:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "5000:5000"
      command: /bin/bash -c "source activate ravenpoint && python3 app.py"


   